spring:
  datasource:
    hashkey: d12b5925c30bfbb623d9a055befee4c1
    hikari:
      driver-class-name: com.mysql.jdbc.Driver
      connection-test-query: SELECT 1
      minimum-idle: 2
      maximum-pool-size: 2
      connection-timeout: 300000
      auto-commit: false
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
  #      jdbc-url: jdbc:mysql://10.162.4.148:13306/payco_redismonitoring_dev?autoReconnect=true&useSSL=false
  #      username: redismonitoring
  #      password: redis!@#123
  jpa:
    open-in-view: false
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: none
    #      naming:
    #        physical-strategy:
    properties:
      hibernate:
        format_sql: true
        physical_naming_strategy: com.alim.allconnp.domain.naming.SnakeCasePhysicalNamingStrategy
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

logging.level:
  org.hibernate.type.descriptor.sql: trace

payco:
  nclavis.phase: real