build.phase: alpha

server:
  tomcat:
    accesslog:
      directory: /home1/irteam/logs/allconnp-api
#      directory: D:/allconnp-api

spring:
  pid:
    file: /home1/irteam/pid/allconnp-api.pid
#    file: D:/allconnp-api

alim:
  cors:
    allowed:
      origins:
        - http://alpha.allconnp.com:10000

logging:
  file:
    name: /home1/irteam/logs/allconnp-api/api.log
#    name: D:/allconnp-api