build.phase: local

spring:
  profiles:
    group:
      local: common,develop-datasource
  pid.file: allconnp-api.pid
  devtools:
    livereload:
      enabled: true

server:
  tomcat:
    accesslog:
      directory: D:/allconnp-api
    #      directory: /Users/danielkim/temp

payco:
  cors:
    allowed:
      origins:
        - http://localhost:3000

logging:
  file:
    name: D:/allconnp-api/web.log
#  name: /Users/danielkim/temp/allconnp-api.log