build.phase: alpha

server:
  tomcat:
    accesslog:
      directory: /home/alim/logs/allconnp-api

spring:
  pid:
    file: /home/alim/logs/allconnp-api.pid

alim:
  cors:
    allowed:
      origins:
        - http://alpha.allconnp.com:3000

logging:
  file:
    name: /home/alim/logs/allconnp-api/api.log