build.phase: release

spring:
  pid.file: /Users/danielkim/logs/allconnp-api.pid
#  redis:
#    cluster.nodes:
#      - 10.160.236.46:10001
#      - 10.160.236.46:10002
#      - 10.160.236.46:10003
#      - 10.160.236.47:10001
#      - 10.160.236.47:10002
#      - 10.160.236.47:10003

server:
  tomcat:
    accesslog:
      directory: /Users/danielkim/logs/allconnp-api

alim:
  cors:
    allowed:
      origins:
        - http://todo:10000

logging:
  level:
    root: info
    jdbc: off
    jdbc.sqlonly: off
    jdbc.sqltiming: info
    com.alim.allconnp: info
    com.alim.starter: info
  file:
    name: /Users/danielkim/logs/allconnp-api/api.log